### ISSUE TITLE
Rules for office BPs 

### ISSUE THREAD

**Issue by mattStorer** [OHSUCMP/mycareplanner#1]
This parameter may be added to any FHIR search. If included, this number sets the maximum number of resources that should be returned per page of results. However, the default JavaScript API for FHIR return all available pages from a single query. So including _count is only useful in our apps if we also override the API to only return one page.

UPDATE FOR 9/125 - REVIEW NEW SCREENSHOT OF REPORTHISTORY

**Increased vitals COUNT to 10**

from MCCVitalSigns.cql:
![image](https://github.com/user-attachments/assets/c0bd7e40-def8-44af-9c26-ab7fe923a1c7)

### Action items:

- Update COUNT to 12 from 10 in FHIR call for office blood pressures.

**Comment by mattStorer** [comment]
I've updated the FHIR query for office BPs to specify `_count=12` instead of `_count=10`.

![image](https://github.com/user-attachments/assets/21aca0a5-6154-4924-ba3a-8104350fd8df)

**Comment by MichelleBobo** [comment]
New requirement is to remove count and use an 18 month lookback period instead.

**Comment by mattStorer** [comment]
Old: Update COUNT to 12 from 10 in FHIR call for office blood pressures. 
11/6/24: New plan pull everything from last 18 months

**Comment by mattStorer** [comment]
this is done
