### ISSUE TITLE
Rules for Home BPs

### ISSUE THREAD

**Issue by mattStorer** [OHSUCMP/mycareplanner#2]
Because home BPs are stored in Epic flowsheet rows with systolic and diastolic as different data points, EMI was concerned that if they capped it at a limit (say 10) than they might get back only 10 systolic, or vice versa
 
So if applying a limit, it needs to be applied downstream after they have been paired back together.

### Action items:

- Implement COUNT on home blood pressures (no COUNT implemented currently, only a 1 year timeframe limit)

**Comment by MichelleBobo** [comment]
New requirement is no COUNT but an 18 month lookback period instead.

**Comment by mattStorer** [comment]
Old: Implement COUNT on home blood pressures (no COUNT implemented currently, only a 1 year timeframe limit) 
11/6/24: New plan pull everything from last 18 months

**Comment by mattStorer** [comment]
this is done
